name: Become The Shadow
favicon: null
layout_spectrum: 0.75178
typography_spectrum: 0.1059
title: One Man's Adventure to Become a Ninja.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70292614-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de1000'
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#8c8c8c'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
