name: Become The Shadow
favicon: null
layout_spectrum: 0.9088829758111387
typography_spectrum: 0.8163008796982467
title: "One Man's Adventure to Become a Ninja."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#bfbfbf'
    - '#555555'
  brandStrength: 0.5
  lightness: 0.13065556506626308
  saturation: 0.11298576835542917
  rhythmicContrast: 0.23912322730757296
purpose: []
