name: Become The Shadow
favicon: null
layout_spectrum: 0.48885
typography_spectrum: 0.03901
title: "One Man's Adventure to Become a Ninja."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#bfbfbf'
    - '#555555'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
