typography_spectrum: 0.1059
color:
  saturation: 0.75
  brandStrength: 0.5
  rhythmicContrast: 0.25
  brandColors:
    - '#de1000'
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#8c8c8c'
  lightness: 0.4375
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: UA-70292614-1
  facebook: null
name: Become The Shadow
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Me
    id: 19b709c1-f78a-4277-81ae-aa4e14125500
    type: content
  - name: Links
    id: 22d88063-731b-4abf-9726-3752d729f7ec
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Become The Shadow
description: One Man's Adventure to Become a Ninja.
purpose: []
