name: Become The Shadow
favicon: null
layout_spectrum: 0.5136
typography_spectrum: 0.04314
title: "One Man's Adventure to Become a Ninja."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70292614-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de1000'
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#8c8c8c'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
