name: Become The Shadow
favicon: null
layout_spectrum: 0.9088829758111387
typography_spectrum: 0.8163008796982467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.11570734228007495
  lightness: 0.13065556506626308
  saturation: 0.11298576835542917
  rhythmicContrast: 0.23912322730757296
purpose: []
