title: One Man's Adventure to Become a Ninja.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  brandStrength: 0.5
  rhythmicContrast: 0.25
  brandColors:
    - '#de1000'
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#8c8c8c'
  lightness: 0.4375
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-70292614-1
  facebook: null
name: Become The Shadow
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1059
layout_spectrum: 1
